apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: z2w7p0811-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-go:9488ba268d61efb2282c187b6ac7df74aad48fbb@sha256:3da29cc4631fd6e0aa986c9ea334a1e1d70aa89aa9a225918cf679ddff5ab327
          name: container-image
