apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: z2w7p0811-go
  janus-idp.io/tekton: z2w7p0811-go
  backstage.io/kubernetes-id: z2w7p0811-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: z2w7p0811-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
