apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: z2w7p0811-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: z2w7p0811-go 
  name: z2w7p0811-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: z2w7p0811-go 
